services:
  - type: web
    name: ragflow-api
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    plan: free
    envVars:
      - key: BRAVE_API_KEY
        sync: false
